# ROS Tutorial Talker
talker:
  # build: ros-tutorials/.
  image: toddsampson:ros-indigo-tutorials
  container_name: talker
  hostname: talker
  name: talker
  # net: rosdocker
  environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  # command: bash
  command: rosrun roscpp_tutorials talker

# ROS Tutorial Listener
listener:
  # build: ros-tutorials/.
  image: toddsampson:ros-indigo-tutorials
  container_name: listener
  hostname: listener
  name: listener
  # net: rosdocker
  environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  # command: bash
  command: rosrun roscpp_tutorials listener

# ROS Structure Sensor
structure_sensor:
  # build: ros-structure_sensor/.
  image: toddsampson/ros-indigo-structure_sensor
  container_name: structure_sensor
  hostname: structure_sensor
  name: structure_sensor
  volumes_from:
      - "rosmaster"
  # net: rosdocker
  devices:
      - "/dev/bus/usb:/dev/bus/usb"
  volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
  environment:
      - "DISPLAY=$DISPLAY"
      - "ROS_HOSTNAME=structure_sensor"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  # command: bash
  command: roslaunch openni2_launch openni2.launch rgb_processing:=False depth_registration:=True

# ROS USBCAM
usbcam:
  # build: ros-usbcam/.
  image: toddsampson/ros-indigo-usbcam
  container_name: usbcam
  hostname: usbcam
  name: usbcam
#    net: rosdocker
  devices:
      - "/dev/bus/usb:/dev/bus/usb"
  environment:
      - "ROS_HOSTNAME=usbcam"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  command: rosrun libuvc_camera camera_node _height:=480 _width:=640 _vendor:=2084 _video_mode:=uncompressed _frame_rate:=30

# ROS Image View
image_view:
  # build: ros-image_pipeline/.
  image: toddsampson/ros-indigo-image_pipeline
  container_name: image_view
  hostname: image_view
  name: image_view
  volumes_from:
      - "rosmaster"
  # net: rosdocker
  volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
  environment:
      - "DISPLAY=$DISPLAY"
      - "ROS_HOSTNAME=image_view"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  command: rosrun image_view image_view image:=/camera/depth_registered/image_raw _baud:=57600

# ROS RVIZ
rviz:
  build: ros-rviz/.
  # image: toddsampson/ros-indigo-rviz
  container_name: rviz
  hostnamename: rviz
  name: rviz
  # net: rosdocker
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
  environment:
      - "DISPLAY=$DISPLAY"
      - "ROS_HOSTNAME=rviz"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  command: rosrun rviz rviz

# ROS MASTER (ROSCORE)
rosmaster:
  image: ros:latest
  container_name: rosmaster
  hostname: rosmaster
  name: rosmaster
  # net: rosdocker
  ports:
       - "11311:11311"
  command: roscore
